org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.11
minecraft_version_range=[1.21.11, 1.22)
neo_version=21.11.45
neo_version_range=[21.11,)
loader_version_range=[10,)

mod_id=enjoy_nights
mod_name=Enjoy nights!
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.coderdiaz.enjoynights
mod_authors=coderdiaz
mod_description=Enhances the Minecraft night experience: prevents skipping the night, turns beds into 10s recovery stations with stamina buffs, disables phantoms, adds lunar phase perks, dark area paranoia, mineral mob drops, and Blood Moon sieges.
